#!/bin/sh

ADGUARD_DIR="/tmp/userdata/AdGuard"
SAFEGATE_DIR="/etc/safegate"
WEBHOOK_URL="https://discord.com/api/webhooks/xxx/xxx"

mkdir -p "$ADGUARD_DIR"
mkdir -p "$SAFEGATE_DIR"
mkdir -p "/tmp/SafeGate"

echo "Checking CA Certificates..."
if [ ! -f "$ADGUARD_DIR/ca-certificates.crt" ]; then
    echo "CA Cert not found. Downloading..."
    /userfs/bin/curl -k -o "$ADGUARD_DIR/ca-certificates.crt" https://curl.se/ca/cacert.pem
fi

echo "Creating AdGuardHome.yaml..."
cat << 'EOF' > "$ADGUARD_DIR/AdGuardHome.yaml"
http:
  pprof:
    port: 6060
    enabled: false
  address: 0.0.0.0:88
  session_ttl: 720h
users:
  - name: AppleSang
    password: $2a$10$mHtioLDUKu3aXhYy73Qqhuvww2ZvkOBYP85UoHKftItIdhep3TBbW
auth_attempts: 5
block_auth_min: 15
http_proxy: ""
language: en
theme: dark
dns:
  bind_hosts:
    - 0.0.0.0
  port: 53
  anonymize_client_ip: false
  ratelimit: 0
  ratelimit_subnet_len_ipv4: 24
  ratelimit_subnet_len_ipv6: 56
  ratelimit_whitelist: []
  refuse_any: true
  upstream_dns:
    - 8.8.8.8
    - 1.0.0.2
    - 76.76.2.2
    - 94.140.14.14
  upstream_dns_file: ""
  bootstrap_dns:
    - 1.1.1.1
  fallback_dns: []
  upstream_mode: load_balance
  fastest_timeout: 1s
  allowed_clients: []
  disallowed_clients: []
  blocked_hosts:
    - version.bind
    - id.server
    - hostname.bind
  trusted_proxies:
    - 127.0.0.0/8
    - ::1/128
  cache_enabled: true
  cache_size: 4194304
  cache_ttl_min: 0
  cache_ttl_max: 0
  cache_optimistic: true
  cache_optimistic_answer_ttl: 30s
  cache_optimistic_max_age: 12h
  bogus_nxdomain: []
  aaaa_disabled: false
  enable_dnssec: false
  edns_client_subnet:
    custom_ip: ""
    enabled: false
    use_custom: false
  max_goroutines: 300
  handle_ddr: true
  ipset: []
  ipset_file: ""
  bootstrap_prefer_ipv6: false
  upstream_timeout: 10s
  private_networks: []
  use_private_ptr_resolvers: false
  local_ptr_upstreams: []
  use_dns64: false
  dns64_prefixes: []
  serve_http3: false
  use_http3_upstreams: false
  serve_plain_dns: true
  hostsfile_enabled: true
  pending_requests:
    enabled: true
tls:
  enabled: false
  server_name: ""
  force_https: false
  port_https: 443
  port_dns_over_tls: 853
  port_dns_over_quic: 853
  port_dnscrypt: 0
  dnscrypt_config_file: ""
  allow_unencrypted_doh: false
  certificate_chain: ""
  private_key: ""
  certificate_path: ""
  private_key_path: ""
  strict_sni_check: false
querylog:
  dir_path: ""
  ignored: []
  interval: 168h
  size_memory: 1000
  enabled: true
  file_enabled: true
statistics:
  dir_path: ""
  ignored: []
  interval: 24h
  enabled: true
filters:
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt
    name: AdGuard DNS filter
    id: 1
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_2.txt
    name: AdAway Default Blocklist
    id: 2
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_16.txt
    name: 'VNM: ABPVN List'
    id: 1757739071
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_59.txt
    name: AdGuard DNS Popup Hosts filter
    id: 1757739333
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_7.txt
    name: Perflyst and Dandelion Sprout's Smart-TV Blocklist
    id: 1757739334
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_61.txt
    name: HaGeZi's Samsung Tracker Blocklist
    id: 1757739335
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_11.txt
    name: Malicious URL Blocklist (URLHaus)
    id: 1757739336
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_50.txt
    name: uBlock₀ filters – Badware risks
    id: 1757739338
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_63.txt
    name: HaGeZi's Windows/Office Tracker Blocklist
    id: 1757765535
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_46.txt
    name: HaGeZi's Anti-Piracy Blocklist
    id: 1765982121
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_67.txt
    name: HaGeZi's Apple Tracker Blocklist
    id: 1765982122
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_47.txt
    name: HaGeZi's Gambling Blocklist
    id: 1765982123
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_66.txt
    name: HaGeZi's OPPO & Realme Tracker Blocklist
    id: 1765982124
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_60.txt
    name: HaGeZi's Xiaomi Tracker Blocklist
    id: 1765982125
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_65.txt
    name: HaGeZi's Vivo Tracker Blocklist
    id: 1765982126
whitelist_filters: []
user_rules:
  - '||samsungcloudcdn.com^'
  - '||samsungqbe.com^'
  - '||heytapdl.com^'
dhcp:
  enabled: false
  interface_name: br0
  local_domain_name: lan
  dhcpv4:
    gateway_ip: 192.168.1.1
    subnet_mask: 255.255.255.0
    range_start: 192.168.1.2
    range_end: 192.168.1.200
    lease_duration: 86400
    icmp_timeout_msec: 1000
    options: []
  dhcpv6:
    range_start: ""
    lease_duration: 86400
    ra_slaac_only: false
    ra_allow_slaac: false
filtering:
  blocking_ipv4: ""
  blocking_ipv6: ""
  blocked_services:
    schedule:
      time_zone: Local
    ids:
      - apple_streaming
      - samsung_tv_plus
  protection_disabled_until: null
  safe_search:
    enabled: false
    bing: true
    duckduckgo: true
    ecosia: true
    google: true
    pixabay: true
    yandex: true
    youtube: true
  blocking_mode: default
  parental_block_host: family-block.dns.adguard.com
  safebrowsing_block_host: standard-block.dns.adguard.com
  rewrites: []
  safe_fs_patterns:
    - /tmp/userdata/ram/userfilters/*
  safebrowsing_cache_size: 1048576
  safesearch_cache_size: 1048576
  parental_cache_size: 1048576
  cache_time: 30
  filters_update_interval: 1
  blocked_response_ttl: 10
  filtering_enabled: true
  rewrites_enabled: true
  parental_enabled: false
  safebrowsing_enabled: false
  protection_enabled: true
clients:
  runtime_sources:
    whois: true
    arp: true
    rdns: true
    dhcp: true
    hosts: true
  persistent: []
log:
  enabled: true
  file: ""
  max_backups: 0
  max_size: 100
  max_age: 3
  compress: false
  local_time: false
  verbose: false
os:
  group: ""
  user: ""
  rlimit_nofile: 0
schema_version: 32
EOF

echo "Creating startup.sh..."
cat << EOF > "$ADGUARD_DIR/startup.sh"
#!/bin/sh
export SSL_CERT_FILE=/tmp/userdata/AdGuard/ca-certificates.crt

mkdir -p /tmp/SafeGate

if [ ! -x /tmp/SafeGate/AdGuardHome/AdGuardHome ]; then
    cd /tmp/SafeGate >/dev/null 2>&1 || exit 1
    /userfs/bin/curl -s -fSL -o AdGuardHome_linux_armv5.tar.gz \\
        https://github.com/AdguardTeam/AdGuardHome/releases/latest/download/AdGuardHome_linux_armv5.tar.gz >/dev/null 2>&1
    tar -xzf AdGuardHome_linux_armv5.tar.gz >/dev/null 2>&1
    rm AdGuardHome_linux_armv5.tar.gz >/dev/null 2>&1
    cd AdGuardHome >/dev/null 2>&1 || exit 1
    chmod +x AdGuardHome >/dev/null 2>&1
else
    cd /tmp/SafeGate/AdGuardHome >/dev/null 2>&1 || exit 1
fi

pidof dnsmasq >/dev/null 2>&1 && kill "\$(pidof dnsmasq)" >/dev/null 2>&1

( ./AdGuardHome -c /tmp/userdata/AdGuard/AdGuardHome.yaml -w /tmp/SafeGate >/dev/null 2>&1 ) &

iptables -I INPUT -p tcp --dport 88 -j ACCEPT >/dev/null 2>&1
EOF
chmod +x "$ADGUARD_DIR/startup.sh"
echo "Creating send_ip.sh..."

cat << EOF > "$SAFEGATE_DIR/send_ip.sh"
#!/bin/sh
exec >/dev/null 2>&1

WEBHOOK="$WEBHOOK_URL"
LAST_IP_FILE="/tmp/last_ip_router_ip.txt"
CURL_BIN="/userfs/bin/curl"
CA_CERT="/tmp/userdata/AdGuard/ca-certificates.crt"

WAN_IP=\$("\$CURL_BIN" -s --cacert "\$CA_CERT" http://pornhub.com 2>/dev/null | sed 's/[[:space:]]//g')

[ -z "\$WAN_IP" ] && exit 1

echo "\$WAN_IP" > "\$LAST_IP_FILE"

PAYLOAD="{\"content\":\"📡 Router IP hiện tại: **\$WAN_IP**\"}"

"\$CURL_BIN" -s -X POST --cacert "\$CA_CERT" \\
    -H "Content-Type: application/json" \\
    -d "\$PAYLOAD" "\$WEBHOOK" >/dev/null 2>&1

iptables -C INPUT -p tcp --dport 22 -j ACCEPT 2>/dev/null || iptables -I INPUT -p tcp --dport 22 -j ACCEPT 2>/dev/null
/tmp/userdata/AdGuard/startup.sh >/dev/null 2>&1 &
EOF

chmod +x "$SAFEGATE_DIR/send_ip.sh"
echo "Overwriting system files..."

OVERWRITE_CONTENT="#!/bin/sh
/etc/safegate/send_ip.sh >/dev/null 2>&1
echo 1
"

echo "$OVERWRITE_CONTENT" > "$SAFEGATE_DIR/md5.sh"
chmod +x "$SAFEGATE_DIR/md5.sh"
echo "$OVERWRITE_CONTENT" > "$SAFEGATE_DIR/init.sh"
chmod +x "$SAFEGATE_DIR/init.sh"
echo "$OVERWRITE_CONTENT" > "$SAFEGATE_DIR/safegate.sh"
chmod +x "$SAFEGATE_DIR/safegate.sh"

echo "Setup completed successfully."
